language: python

python: "2.7"

sudo: false

cache:
    directories:
        - $HOME/.pip-cache/
        - _build

install: pip install --download-cache $HOME/.pip-cache --user sphinx==1.1.3

script: sphinx-build -nW -b html -d _build/doctrees . _build/html

branches:
  except:
    - github-comments
